spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hubr
    username: geek
    password: geek

  liquibase:
    change-log: classpath:/liquibase/changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: validate
